# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-altera-openbmc"
BBFILE_PATTERN_meta-altera-openbmc = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-altera-openbmc = "7"

LAYERDEPENDS_meta-altera-openbmc = "core phosphor-layer altera-bsp"
LAYERSERIES_COMPAT_meta-altera-openbmc = "wrynose"
