# Disable mutual TLS authentication for this board.
#
# meta-phosphor enables mutual-tls-auth by default in its PACKAGECONFIG.
# Mutual TLS requires the browser/client to present a client certificate in
# addition to the server's certificate — this is not set up on the dev board
# and causes all HTTPS connections to be rejected with a TLS handshake error.
#
# Standard username/password authentication via HTTPS is sufficient. The
# server-side TLS certificate (generated by
# phosphor-certificate-manager@bmcweb.service on first boot) is still used,
# so the HTTPS transport is encrypted. Only the mTLS client-certificate
# requirement is removed.
PACKAGECONFIG:remove = "mutual-tls-auth"

# NOTE: AMI's meta-agilex3/meta-custom also repoints bmcweb SRC_URI/SRCREV at
# their git.ami.com one-tree fork (a known-good AArch64 commit) to avoid a
# startup SIGSEGV seen with the GitHub fork commit. That fork requires the
# git-lfs webui-libraries pull we are deliberately deferring, so we keep the
# upstream/meta-ami bmcweb here for now and will revisit the fork when we
# integrate AMI's webui-vue. The mTLS + cert-ordering fixes below are safe and
# apply regardless of which bmcweb source is used.

# Install a systemd drop-in that orders bmcweb.service AFTER
# phosphor-certificate-manager@bmcweb.service so that the TLS server
# certificate is guaranteed to exist before bmcweb tries to load it.
# Without this, bmcweb races the cert generator on first boot, crashes
# (SIGSEGV in ssl::context::use_certificate_file), hits the restart
# rate-limit, and the web UI stays permanently unavailable.
FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"

SRC_URI:append = " \
    file://bmcweb.service.d/10-cert-dependency.conf \
"

do_install:append() {
    install -d ${D}${systemd_system_unitdir}/bmcweb.service.d
    install -m 0644 ${UNPACKDIR}/bmcweb.service.d/10-cert-dependency.conf \
        ${D}${systemd_system_unitdir}/bmcweb.service.d/10-cert-dependency.conf
}

FILES:${PN} += "${systemd_system_unitdir}/bmcweb.service.d/10-cert-dependency.conf"
